#!/bin/bash
yes| termux-setup-storage > /dev/null 2>&1
clear
Menu() {
    clear
    echo -e '\n'
    echo -e "\e[01;37;41m           EITAAAH! NETMODZ          \e[0m"; sleep .4; echo
    echo " Ocorreu um erro, tente novamente mais tarde."
    echo "Não foi possivel conectar ao servidor"
    echo "Todos os servidor da netmodz esta em atualização"
    echo "=========================="
    echo "[0] SAIR"
    echo -e '\n'
    echo "Algo deu errado"
    echo "Tente novamente mais tarde."	
    read App
    case $App in
   
    0) Sair ;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    }

Voltar() {
clear
Menu
}

Sair() {
clear
exit
}
clear
Menu
